name: Train Linear Regression

on: workflow_dispatch

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "Cohort-1/LinearRegression/requirements.txt"

      - name: Run training on the Ray cluster
        id: run-training
        env:
            WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          cd Cohort-1/LinearRegression
          RAY_ADDRESS='http://3.15.175.158:8265' ray job submit --no-wait --entrypoint-num-cpus 1 --runtime-env-json "{\"env_vars\":{\"WANDB_API_KEY\":\"$WANDB_API_KEY\"}}" --working-dir . -- python train.py
