name: Train YOLOv8

on: workflow_dispatch

env:
  AWS_REGION: us-east-1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "Cohort-1/ray-cluster/requirements.txt"

      - name: Run training on the Ray cluster
        id: run-training-yolov8
        env:
            WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          cd Cohort-1/YOLOv8
          RAY_ADDRESS='http://3.15.175.158:8265' ray job submit --no-wait --entrypoint-num-cpus 1 --runtime-env-json "{\"env_vars\":{\"WANDB_API_KEY\":\"$WANDB_API_KEY\"}}" --working-dir . -- python yolov8.py
