name: Deploy YOLOv8

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.9'

      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "Cohort-1/ray-cluster/requirements.txt"

      - name: Deploy YOLOv8 to the Ray cluster
        id: deploy-yolov8
        env:
            WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        run: |
          cd Cohort-1/YOLOv8
          RAY_ADDRESS='http://3.15.175.158:8265' ray job submit --no-wait--working-dir . -- sh deploy_script.sh
